import {
  Siren,
  Syringe,
  Weight,
  HeartPulse,
  Activity,
  ShieldPlus,
  Smile,
  TestTubeDiagonal,
  Ear,
  Users,
  UtensilsCrossed,
  Stethoscope,
  Scissors,
  ScanLine,
  Pill,
  Droplets,
  Brain,
  BrainCog,
  Venus,
  Bone,
  Baby,
  PillBottle,
  BrainCircuit,
  Dumbbell,
  ShieldCheck,
  Wind,
  Radiation,
  ScissorsSquare,
  ScissorsLineDashed,
  Droplet,
  Waves,
  type LucideIcon,
} from "lucide-react";

const departmentIconMap: Record<string, LucideIcon> = {
  "accident-emergency": Siren,
  anaesthesiology: Syringe,
  "bariatric-surgery": Weight,
  cardiology: HeartPulse,
  "cardiothoracic-vascular-surgery": Activity,
  "critical-care-toxicology": ShieldPlus,
  dental: Smile,
  diabetology: TestTubeDiagonal,
  ent: Ear,
  "family-medicine": Users,
  gastroenterology: UtensilsCrossed,
  "general-medicine": Stethoscope,
  "general-surgery": Scissors,
  "imaging-sciences-interventional-radiology": ScanLine,
  "medical-oncology": Pill,
  nephrology: Droplets,
  neurology: Brain,
  "neuro-surgery": BrainCog,
  "obstetrics-gynaecology": Venus,
  orthopaedics: Bone,
  "pediatric-surgery": Baby,
  pediatrics: Baby,
  pharmacy: PillBottle,
  "psychiatric-counselling": BrainCircuit,
  "physical-medicine-rehabilitation": Dumbbell,
  "preventive-medicine": ShieldCheck,
  pulmonology: Wind,
  "radiation-oncology": Radiation,
  oncology: Radiation,
  "surgical-gastroenterology": ScissorsSquare,
  "surgical-oncology": ScissorsLineDashed,
  urology: Droplet,
  "vascular-surgery": Waves,
};

export function getDepartmentIcon(slug: string): LucideIcon {
  return departmentIconMap[slug] ?? Stethoscope;
}
